export const LOAD_BUILD_SLACK = 'LOAD_BUILD_SLACK';
export const LOAD_BUILD_SLACK_SUCCESS = 'LOAD_BUILD_SLACK_SUCCESS';
export const LOAD_BUILD_SLACK_FAILURE = 'LOAD_BUILD_SLACK_FAILURE';

export const LOAD_MONGO_TEST = 'LOAD_MONGO_TEST'; 
export const LOAD_MONGO_TEST_SUCCESS = 'LOAD_MONGO_TEST_SUCCESS';
export const LOAD_MONGO_TEST_FAILURE = 'LOAD_MONGO_TEST_FAILURE';